from __future__ import annotations

import json
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
MODULE = ROOT / "src" / "kokoro_tts" / "static" / "admin" / "presentation.js"
ADMIN = ROOT / "src" / "kokoro_tts" / "static" / "admin.js"


def _node(script: str) -> dict[str, object]:
    completed = subprocess.run(
        ["node", "--input-type=module", "--eval", script],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(completed.stdout)


COPY = """
const copy = {
  healthOk: 'HEALTHY', healthErrors: count => `ERRORS:${count}`,
  metricCurrentModel: 'CURRENT', metricLoaded: 'LOADED', metricActiveRequests: 'ACTIVE',
  metricCache: 'CACHE', metricSuccessFailure: 'SUCCESS/FAILURE', metricAverageTime: 'AVERAGE',
  metricMaxSilence: 'MAX SILENCE', metricClipRatio: 'CLIP', providerFallbackCpu: 'FALLBACK CPU',
  modelError: 'ERROR', modelLoaded: 'LOADED', modelSleepingOnDemand: 'SLEEP ON DEMAND',
  modelSleeping: 'SLEEPING', modelUnloaded: 'UNLOADED', processIsolated: 'ISOLATED',
  worker: 'WORKER', workerOnline: 'ONLINE', workerExited: 'EXITED', threadLocalMemory: 'THREAD LOCAL',
  current: 'CURRENT', cache: 'CACHE', cacheOccupied: 'OCCUPIED', empty: 'EMPTY', modes: 'MODES',
  longSilence: 'LONG SILENCE', timeout: 'TIMEOUT', pendingRebuild: 'PENDING REBUILD',
  memoryReclaimable: 'RECLAIMABLE', lowVram: 'LOW VRAM', vramNormal: 'VRAM NORMAL',
  fallbackReason: 'FALLBACK:', load: 'LOAD', switch: 'SWITCH', unload: 'UNLOAD',
  forceStop: 'FORCE STOP', checkAssets: 'CHECK ASSETS', repairAssets: 'REPAIR ASSETS',
  emptyModels: 'NO MODELS', restart: 'RESTART', rebuild: 'REBUILD', immediate: 'IMMEDIATE',
  byteFieldHint: 'BYTE HINT', enabled: 'ENABLED', disabled: 'DISABLED',
  autoGenerated: 'AUTO', manualOrEnvironment: 'MANUAL',
  apiKeyStatus: (state, source, preview) => `KEY:${state}:${source}:${preview}`,
  publicModelList: 'PUBLIC', trustProxyIp: 'PROXY', downloadSource: 'SOURCE',
  configFile: 'CONFIG FILE', persistentOverrides: 'OVERRIDES', adminCredentialSource: 'AUTH SOURCE',
  credentialPersistence: 'PERSISTENCE', yes: 'YES', no: 'NO', none: 'NONE',
  itemCount: count => `ITEMS:${count}`, hashSaved: 'HASH SAVED', notSaved: 'NOT SAVED',
  vramRemaining: 'VRAM REMAINING', vramMode: 'VRAM MODE', lowVramProtection: 'LOW PROTECTION',
  decodeProtection: 'DECODE PROTECTION', normal: 'NORMAL', maxSilence: 'MAX SILENCE',
  silenceRatio: 'SILENCE RATIO', clipping: 'CLIPPING', repairedImpulses: 'REPAIRED', peak: 'PEAK',
  characters: 'CHARS', emptyRequests: 'NO REQUESTS',
};
"""


def test_module_is_pure_native_esm_and_admin_is_the_composition_root() -> None:
    result = _node(
        f"""
        for (const name of ['window', 'document', 'fetch', 'localStorage']) {{
          Object.defineProperty(globalThis, name, {{
            configurable: true,
            get() {{ throw new Error(`import touched ${{name}}`); }},
          }});
        }}
        const module = await import({json.dumps(MODULE.as_uri())});
        console.log(JSON.stringify({{ exports: Object.keys(module) }}));
        """
    )
    assert set(result["exports"]) == {
        "bytesToMiB",
        "configFieldHtml",
        "configPresentation",
        "configTabsPresentation",
        "escapeHtml",
        "fieldBadgeHtml",
        "formatBytes",
        "healthPresentation",
        "isByteConfigField",
        "metricCardHtml",
        "metricsHtml",
        "miBToBytes",
        "modelCardHtml",
        "modelsHtml",
        "profilesPresentation",
        "providerLabel",
        "qualityHtml",
        "requestsHtml",
        "securityPresentation",
    }
    source = MODULE.read_text(encoding="utf-8")
    for forbidden in ("window", "document", "fetch", "localStorage", "setTimeout", "common/i18n", "translate"):
        assert forbidden not in source
    assert not re.search(r"[\u3400-\u9fff]", source)
    admin = ADMIN.read_text(encoding="utf-8")
    assert "from './admin/presentation.js'" in admin
    assert "function currentAdminPresentationCopy()" in admin
    assert "function shortNumber(value)" in admin
    assert "document.addEventListener('angevoice:locale-changed'" in admin


def test_formatters_cover_boundaries_and_provider_variants() -> None:
    result = _node(
        f"""
        import * as p from {json.dumps(MODULE.as_uri())};
        {COPY}
        console.log(JSON.stringify({{
          bytes: [0, -1, NaN, 1, 1023, 1024, 1048576, 1073741824].map(p.formatBytes),
          toMiB: [p.bytesToMiB(0), p.bytesToMiB(-1), p.bytesToMiB(NaN), p.bytesToMiB(1572864)],
          toBytes: [p.miBToBytes(0), p.miBToBytes(-1), p.miBToBytes(1.5), String(p.miBToBytes(NaN))],
          byteFields: [
            p.isByteConfigField({{ type: 'int', key: 'cache_bytes' }}),
            p.isByteConfigField({{ type: 'int', key: 'max_bytes_limit' }}),
            p.isByteConfigField({{ type: 'float', key: 'cache_bytes' }}),
          ],
          providers: [
            p.providerLabel({{ actual_provider: 'cuda_pytorch' }}, copy),
            p.providerLabel({{ device: 'cuda' }}, copy),
            p.providerLabel({{ provider: 'cpu_onnx_int8' }}, copy),
            p.providerLabel({{ provider: 'cpu', fallback: true }}, copy),
            p.providerLabel({{ provider: 'Custom' }}, copy),
          ],
        }}));
        """
    )
    assert result["bytes"] == ["0 B", "0 B", "0 B", "1 B", "1023 B", "1.0 KB", "1.0 MB", "1.0 GB"]
    assert result["toMiB"] == [0, 0, 0, 1.5]
    assert result["toBytes"] == [0, -1048576, 1572864, "NaN"]
    assert result["byteFields"] == [True, True, False]
    assert result["providers"] == ["CUDA", "CUDA", "CPU ONNX INT8", "CPU · FALLBACK CPU", "custom"]


def test_health_metrics_and_models_matrix_is_frozen_and_safe() -> None:
    result = _node(
        f"""
        import * as p from {json.dumps(MODULE.as_uri())};
        {COPY}
        const attack = '<img src=x onerror="boom()">';
        const models = [
          {{ id: attack, name: attack, current: true, loaded: true, healthy: true, actual_provider: 'cuda',
             active_count: 2, modes: [attack], process_isolated: false,
             last_output_quality: {{ max_silence_ms: 12, clip_ratio: 0.2 }} }},
          {{ id: 'bad', loaded: true, healthy: false, process_isolated: true, process_alive: true,
             worker_pid: attack, fallback: true, fallback_reason: attack, provider: 'cpu', low_vram_mode: true }},
          {{ id: 'sleep', loaded: false, idle_unloaded: true, process_isolated: false }},
          {{ id: 'isolated', loaded: false, process_isolated: true, process_alive: false, pending_rebuild: true }},
        ];
        const input = Object.freeze({{ models: Object.freeze(models), current_model: attack,
          cache_items: 2, cache_bytes: 1024, stats: Object.freeze({{ requests_ok: 0, requests_error: 1 }}) }});
        const before = JSON.stringify(input);
        const health = p.healthPresentation(models, copy);
        const metrics = p.metricsHtml(input, copy);
        const html = p.modelsHtml(input, copy);
        console.log(JSON.stringify({{
          health, healthFrozen: Object.isFrozen(health), metrics, html,
          unchanged: before === JSON.stringify(input), empty: p.modelsHtml({{ models: [] }}, copy),
          unsafeTags: /<(img|script)\b/i.test(html), escapedModes: html.includes('&lt;img'),
        }}));
        """
    )
    assert result["health"] == {"label": "ERRORS:1", "ok": False, "error": True}
    assert result["healthFrozen"] is True
    assert result["unchanged"] is True
    assert "AVERAGE</span><strong title=\"-\">-" in result["metrics"]
    assert result["empty"] == '<p class="empty-state">NO MODELS</p>'
    assert result["unsafeTags"] is False
    assert result["escapedModes"] is True


def test_config_profiles_security_quality_and_requests_are_pure_and_safe() -> None:
    result = _node(
        f"""
        import * as p from {json.dumps(MODULE.as_uri())};
        {COPY}
        const attack = '\"><script>boom()</script><img src=x onerror=boom()>';
        const payload = {{
          values: {{ enabled: true, choice: 'b', count: 3, ratio: 0.5, text: attack, cache_max_bytes: 67108864, advanced: attack, text_mode: 'legacy' }},
          schema: {{
            groups: [{{ key: 'first', label: attack }}, {{ key: 'second', label: 'Second' }}, {{ key: 'text', label: 'Text' }}],
            fields: [
              {{ key: 'enabled', group: 'first', type: 'bool', label: attack, help: attack }},
              {{ key: 'choice', group: 'first', type: 'choice', label: 'Choice', choices: [{{ value: 'a', label: attack }}, {{ value: 'b', label: 'B' }}] }},
              {{ key: 'count', group: 'first', type: 'int', label: 'Count', min: 1, max: 9, step: 1, restart: true }},
              {{ key: 'ratio', group: 'first', type: 'float', label: 'Ratio', min: 0, max: 1, step: 0.1, rebuild_moss: true }},
              {{ key: 'text', group: 'first', type: 'string', label: 'Text' }},
              {{ key: 'cache_max_bytes', group: 'first', type: 'int', label: 'Bytes', min: 1048576, max: 134217728 }},
              {{ key: 'advanced', group: 'first', type: 'string', label: attack, advanced: true }},
              {{ key: 'text_mode', group: 'text', type: 'choice', label: attack, choices: [{{ value: 'legacy', label: attack }}] }},
            ],
            profiles: [
              {{ key: attack, label: attack, description: attack }},
              {{ key: 'deploy_safe', label: attack, description: attack }},
            ],
          }},
        }};
        const before = JSON.stringify(payload);
        const config = p.configPresentation(payload, 'missing', copy);
        const profiles = p.profilesPresentation(payload);
        const security = p.securityPresentation({{
          security: {{ api_key_enabled: true, api_key_preview: attack, admin_auth_source: attack,
            admin_default_credentials_active: true, admin_security_warning: attack, admin_credentials: {{ persisted: true }} }},
          config: {{ public_status_endpoints: true, trust_proxy_headers: false, model_source: attack,
            runtime_config_file: attack, runtime_config: {{ exists: true, field_count: 2 }} }},
        }}, copy);
        const quality = p.qualityHtml({{ models: [{{ current: true, low_vram_mode: true,
          vram: {{ free_mb: 1, total_mb: 2 }}, last_output_quality: {{ silence_ratio: 0.125, clip_ratio: 0.00123 }} }}] }}, copy);
        const requests = p.requestsHtml({{ active_requests: Array.from({{ length: 8 }}, (_, index) => ({{
          model: index === 7 ? attack : `m${{index}}`, voice: attack, status: attack, error: attack,
          chars: index, elapsed_seconds: index, updated_at: index,
        }})) }}, copy);
        const combined = [config.tabsHtml, config.standardHtml, config.advancedHtml, config.textHtml,
          profiles.tuningHtml, profiles.deployHtml, security.summaryHtml, quality, requests].join('');
        console.log(JSON.stringify({{
          activeGroup: config.activeGroup, hasAdvanced: config.hasAdvanced,
          configFrozen: Object.isFrozen(config), profilesFrozen: Object.isFrozen(profiles), securityFrozen: Object.isFrozen(security),
          unchanged: before === JSON.stringify(payload), unsafeTags: /<(img|script)\b/i.test(combined),
          standard: config.standardHtml, advanced: config.advancedHtml, text: config.textHtml,
          tuning: profiles.tuningHtml, deploy: profiles.deployHtml, security, quality,
          requestCount: (requests.match(/request-item/g) || []).length,
          firstRequest: requests.indexOf('m7') < requests.indexOf('m6'), emptyRequests: p.requestsHtml({{ active_requests: [] }}, copy),
        }}));
        """
    )
    assert result["activeGroup"] == "first"
    assert result["hasAdvanced"] is True
    assert result["configFrozen"] is result["profilesFrozen"] is result["securityFrozen"] is True
    assert result["unchanged"] is True
    assert result["unsafeTags"] is False
    assert 'type="checkbox" checked' in result["standard"]
    assert 'value="b" selected' in result["standard"]
    assert 'type="number" value="3" min="1" max="9" step="1"' in result["standard"]
    assert 'data-config-unit="mib"' in result["standard"]
    assert 'value="64" min="1" max="128" step="1"' in result["standard"]
    assert "BYTE HINT" in result["standard"]
    assert result["requestCount"] == 6
    assert result["firstRequest"] is True
    assert result["emptyRequests"] == '<p class="empty-state">NO REQUESTS</p>'
    assert result["security"]["showWarning"] is True
    assert "12.5%" in result["quality"] and "0.123%" in result["quality"]


def test_copy_is_resolved_per_call_without_locale_cache() -> None:
    result = _node(
        f"""
        import {{ modelsHtml, healthPresentation }} from {json.dumps(MODULE.as_uri())};
        {COPY}
        const second = {{ ...copy, emptyModels: 'SECOND EMPTY', healthOk: 'SECOND HEALTH', forceStop: 'SECOND FORCE' }};
        const model = {{ id: 'model', loaded: true, healthy: true }};
        console.log(JSON.stringify({{
          firstEmpty: modelsHtml({{ models: [] }}, copy),
          secondEmpty: modelsHtml({{ models: [] }}, second),
          firstModel: modelsHtml({{ models: [model] }}, copy),
          secondModel: modelsHtml({{ models: [model] }}, second),
          firstHealth: healthPresentation([model], copy).label,
          secondHealth: healthPresentation([model], second).label,
        }}));
        """
    )
    assert "NO MODELS" in result["firstEmpty"]
    assert "SECOND EMPTY" in result["secondEmpty"]
    assert "FORCE STOP" in result["firstModel"]
    assert "SECOND FORCE" in result["secondModel"]
    assert result["firstHealth"] == "HEALTHY"
    assert result["secondHealth"] == "SECOND HEALTH"


def test_model_numeric_fields_copy_values_and_metric_tone_are_escaped() -> None:
    result = _node(
        f"""
        import * as p from {json.dumps(MODULE.as_uri())};
        {COPY}
        const attacks = [
          '<img src=x onerror="window.__adminInjected=true">',
          '\"><script>window.__adminInjected=true</script>',
        ];
        const model = {{
          id: 'model-id', name: 'Model', current: true, loaded: true, healthy: true,
          modes: ['fast'], process_isolated: false, consecutive_timeouts: 0,
          last_output_quality: {{ long_silence_count: 0 }},
        }};
        const copyAttack = {{ ...copy,
          current: attacks[0], cache: attacks[0], cacheOccupied: attacks[0], empty: attacks[0],
          modes: attacks[0], longSilence: attacks[0], timeout: attacks[0], pendingRebuild: attacks[0],
          memoryReclaimable: attacks[0], lowVram: attacks[0], vramNormal: attacks[0],
          fallbackReason: attacks[0], load: attacks[0], switch: attacks[0], unload: attacks[0],
          checkAssets: attacks[0], repairAssets: attacks[0], emptyModels: attacks[0],
          restart: attacks[0], rebuild: attacks[0], immediate: attacks[0], characters: attacks[0], emptyRequests: attacks[0],
        }};
        const backend = attacks.flatMap(attack => [
          {{ field: 'long_silence_count', attack, html: p.modelCardHtml({{ ...model,
            last_output_quality: {{ long_silence_count: attack }} }}, copy) }},
          {{ field: 'consecutive_timeouts', attack, html: p.modelCardHtml({{ ...model,
            consecutive_timeouts: attack }}, copy) }},
        ]);
        const copyHtml = [
          p.modelCardHtml({{ ...model, pending_rebuild: true, fallback_reason: 'fallback' }}, copyAttack),
          p.modelsHtml({{ models: [] }}, copyAttack),
          p.fieldBadgeHtml({{ restart: true }}, copyAttack),
          p.fieldBadgeHtml({{ rebuild_moss: true }}, copyAttack),
          p.fieldBadgeHtml({{}}, copyAttack),
          p.requestsHtml({{ active_requests: [{{ model: 'model', voice: 'voice', status: 'done', chars: 3, elapsed_seconds: 1 }}] }}, copyAttack),
          p.requestsHtml({{ active_requests: [] }}, copyAttack),
        ].join('');
        const toneHtml = p.metricCardHtml('Metric', 'Value', '\" onclick=\"window.__adminInjected=true');
        const escaped = html => !/<(img|script)\\b/i.test(html) && !html.includes('&amp;lt;');
        const normal = p.modelCardHtml(model, copy);
        console.log(JSON.stringify({{
          backend: backend.map(item => ({{ ...item, safe: escaped(item.html), imageEncoded: item.html.includes('&lt;img'), scriptEncoded: item.html.includes('&lt;script&gt;') }})),
          copySafe: escaped(copyHtml), copyEncoded: copyHtml.includes('&lt;img'),
          toneSafe: escaped(toneHtml), toneHtml,
          normal,
        }}));
        """
    )
    assert len(result["backend"]) == 4
    assert {item["field"] for item in result["backend"]} == {"long_silence_count", "consecutive_timeouts"}
    assert all(item["safe"] and (item["imageEncoded"] or item["scriptEncoded"]) for item in result["backend"])
    assert result["copySafe"] is True
    assert result["copyEncoded"] is True
    assert result["toneSafe"] is True
    assert 'class="metric-card admin-metric "' in result["toneHtml"]
    assert "onclick=" not in result["toneHtml"]
    assert "CURRENT" in result["normal"]
    assert "CACHE OCCUPIED" in result["normal"]
